<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>Cinema_Management_App</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UserSecretsId>08ecfdc0-d62a-43d9-8154-46944b3a56a9</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Resources\icon\cinema.png" />
    <None Remove="Resources\icon\home.png" />
    <None Remove="Resources\icon\money.png" />
    <None Remove="Resources\icon\more.png" />
    <None Remove="Resources\icon\movie-reel.png" />
    <None Remove="Resources\icon\settings.png" />
    <None Remove="Resources\icon\ticket.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="DotNetEnv" Version="3.1.1" />
    <PackageReference Include="MaterialDesignThemes" Version="5.3.2" />
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="10.0.5" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.5" />
    <PackageReference Include="MySql.Data" Version="9.6.0" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="10.0.5" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\icon\cinema.png" />
    <Resource Include="Resources\icon\home.png" />
    <Resource Include="Resources\icon\money.png" />
    <Resource Include="Resources\icon\more.png" />
    <Resource Include="Resources\icon\movie-reel.png" />
    <Resource Include="Resources\icon\settings.png" />
    <Resource Include="Resources\icon\ticket.png" />
  </ItemGroup>

</Project>
